<?php

namespace app\api\controller;

use think\Controller;
use think\Request;

class City extends Controller
{
    private $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\City();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function getCitysByParentId()
    {
        $id=input('post.id',0,'intval');
        if(!$id)
        {
            $this->error('ID不合法');
        }
        //通过ID获取耳机城市
        $citys=$this->db->getNormalCity($id);
        if(!$citys)
        {
            return show(0,'error');
        }
          return show(1,'success',$citys);
    }


}
